// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqJJkV7JVOjfKXyT4LmIoeADPZl8O6tVM',
    appId: '1:555275914178:web:5347f02ccf879e17aa245b',
    messagingSenderId: '555275914178',
    projectId: 'facebook-a754b',
    authDomain: 'facebook-a754b.firebaseapp.com',
    storageBucket: 'facebook-a754b.firebasestorage.app',
    measurementId: 'G-N68WWTJQ1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgz_7J1C09f_7ND_XxIBVRQ9YdROIv43w',
    appId: '1:555275914178:android:641b094d8c7fb089aa245b',
    messagingSenderId: '555275914178',
    projectId: 'facebook-a754b',
    storageBucket: 'facebook-a754b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVCNBj3vfiHH9GMso0m6B8aTP_W4A_giU',
    appId: '1:555275914178:ios:b9ffc9c88b374a90aa245b',
    messagingSenderId: '555275914178',
    projectId: 'facebook-a754b',
    storageBucket: 'facebook-a754b.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVCNBj3vfiHH9GMso0m6B8aTP_W4A_giU',
    appId: '1:555275914178:ios:b9ffc9c88b374a90aa245b',
    messagingSenderId: '555275914178',
    projectId: 'facebook-a754b',
    storageBucket: 'facebook-a754b.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqJJkV7JVOjfKXyT4LmIoeADPZl8O6tVM',
    appId: '1:555275914178:web:2734696dc4e0ceafaa245b',
    messagingSenderId: '555275914178',
    projectId: 'facebook-a754b',
    authDomain: 'facebook-a754b.firebaseapp.com',
    storageBucket: 'facebook-a754b.firebasestorage.app',
    measurementId: 'G-08NNM75WYV',
  );
}
